### ISSUE TITLE
Modals have incorrect bottom padding with empty modal actions container

### ISSUE THREAD

**Issue by astorije-vmware** [vmware-clarity/core#187]
## Describe the bug

<img width="592" alt="Screen Shot 2022-10-27 at 6 42 58 PM" src="https://user-images.githubusercontent.com/90871916/198411625-b33a530d-9be5-4b15-a763-824730983626.png">
<img width="597" alt="Screen Shot 2022-10-27 at 6 43 10 PM" src="https://user-images.githubusercontent.com/90871916/198411641-a241af01-eb5a-4e72-86e5-cd7348ba6e9b.png">

## How to reproduce

1.  Go to https://codesandbox.io/s/cds-modal-actions-padding-b1fl7t
2.  You will need to open the preview in a dedicated window. Click "Open in New Window"
3.  Open modal 1 to see the correct padding, modal 2 for the incorrect padding

## Expected behavior

Both modal 1 and 2 should look identical.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [x] v6.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**

React 18

## Additional notes

**Why rendering an empty `CdsModalActions` in the first place?**

We need empty actions because we display the action button conditionally. We initially wrapped the conditional around the entire container (instead of just the button) as a workaround, but another issue kicked in: when the modal is opened and the actions container is meant to render later, it simply... does not appear.

I opened https://github.com/vmware-clarity/core/issues/188 to report this behavior as well.

**Comment by ashleyryan** [comment]
cds-modal-actions is an html element. If instead of a component, you were to render `<div class="my-footer"></div>` you wouldn't expect it to behave any differently than it does now. Yes, you're going to get a gap between the body and the actions when you include the `cds-modal-actions` element, just like if you used a div. They're both HTML Elements. 

Looping @colinreedmiller in to chime in, but I don't think this is something we'll fix (I will try and fix the linked issue, however).
