### ISSUE TITLE
CdsModalActions is not visible when rendered after a timeout

### ISSUE THREAD

**Issue by astorije-vmware** [vmware-clarity/core#188]
## Describe the bug

When `CdsModalActions` is rendered after a timeout, nothing appears. This is better demonstrated on the sandbox below.

## How to reproduce

1.  Go to https://codesandbox.io/s/cds-modal-actions-timeout-7xpf0c
2.  Click on "Open modal"
3.  Wait 3 seconds to see the content change. When that happens, the actions should be visible as well, but they are not.

## Expected behavior

The button should appear at the same time as the content changes.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [x] v6.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**

React 18

## Additional notes

This can be mitigated by rendering the button conditionally only, and not the `CdsModalActions` container, but when doing so I run into #187.

**Comment by ashleyryan** [comment]
I think I know why this is happening and I'm trying to think of the best way to fix it without messing up all of the CSS. 

[We conditionally render the footer slot, if it's supplied](https://github.com/vmware-clarity/core/blob/main/projects/core/src/modal/modal.element.ts#L95). This works for the first render. The problem is that after the first render, that slot no longer exists, so when you try and add content with that slot name, it has nowhere to go. I think we need to get rid of the `gap` the cds-layout uses and conditionally apply top margin if the footer slot exists instead.
